title = "Atomic Thoughts"
author = "Jared Connor"
languagecode = "en"
theme = "piovoso"
googleAnalytics = "G-ECQJXP6HMT" 

[params]
  description = "description"
  avatar = "img/url"
  favicon = "img/url"

[menu]
  [[menu.main]]
    name = 'About'
    url = 'about'
    weight = 1
  [[menu.main]]
    name = 'Blog'
    url = 'blog'
    weight = 2
  [[menu.main]]
    name = 'Projects'
    url = 'project'
    weight = 3
  [[menu.social]] 
    name = 'Github'
    url = 'https://github.com/jaredtconnor'
    weight = 1 
    pre='fa-brands fa-github'
  [[menu.social]]
    name = 'Rss'
    url = 'index.xml'
    weight = 2 
    pre='fa-solid fa-rss' 
  [[menu.social]]
    name = 'Twitter'
    url = 'https://twitter.com/Jared_ThomasC'
    weight = 3 
    pre='fa-brands fa-twitter'  
  [[menu.social]]
    name = 'LinkedIn'
    url = 'https://www.linkedin.com/in/jaredconnor/'
    weight = 4
    pre='fa-brands fa-linkedin'  
  [[menu.social]]
    name = 'Mail'
    url = 'mailto:info@jaredtconnor.com'
    weight = 5
    pre='fa-solid fa-envelope'  
