title = "Signs of Improvement"
author = "Jared Connor"
languagecode = "en"
theme = "piovoso"

[params]
  description = "description"
  avatar = "img/url"
  favicon = "img/url"

[menu]
  [[menu.main]]
    name = 'About'
    url = 'about'
    weight = 1
  [[menu.main]]
    name = 'Blog'
    url = 'blog'
    weight = 2
  [[menu.main]]
    name = 'Projects'
    url = 'project'
    weight = 3
  [[menu.main]]
    name = 'Github'
    url = 'https://github.com/jaredtconnor'
    weight = 4
  [[menu.main]]
    name = 'Twitter'
    url = 'https://twitter.com/Jared_ThomasC'
    weight = 5