title = "Signs of Improvement"
author = "Jared Connor"
languagecode = "en"
theme = "piovoso"

[params]
  description = "description"
  avatar = "img/url"
  favicon = "img/url"

[menu]
  [[menu.navigation]]
    name = 'link'
    url = 'link'
    