baseURL = "https://www.jaredtconnor.com/"
languageCode = "en-us"
title = "Jared Connor"
theme = "noteworthy"
enableRobotsTXT = true
paginate = 4 # Set the number of posts to show before overflowing to the next page.
summaryLength = 10 # Configure how long the post summary should be on the homepage.

# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalytics = "" 

[taxonomies]
  tag = "tags"

[author]
	name = "Jared Connor"

# Set to false to disallow raw HTML in markdown files
[markup.goldmark.renderer]
    unsafe = true

[params]
	math = true
	
  description = ""

    showReadMore = false
  
  # Social Accounts and Icons
	email = "jaredconnor301@gmail.com"
  twitter = "https://twitter.com/Jared_ThomasC"
  linkedin = "https://www.linkedin.com/in/jaredconnor/"
  github = "https://github.com/jaredtconnor"

# Menu links along the sidebar navigation.
[[menu.main]]
	identifier = "about"
	name = "About"
	url = "/about/"
	weight = 1

[[menu.main]]
	identifier = "blog" 
	name = "Blog"
	url = ""
	weight = 2

[[menu.main]]
	identifier = "projects"
	name = "Projects"
	url = "/projects/"
	weight = 3

[[menu.main]]
	identifier = "archives"
	name = "Archives"
	url = "/archives/"
	weight = 4

# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false