baseurl = "https://www.jaredtconnor.com/"
title = "Jared Connor"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "#"

[params]
    author = "Jared Connor"
    info = "Financial Analyst for Umpqua Bank"
    description = "Jared Connor's personal website and blog"
    keywords = "blog,developer,personal,economics,finance,analyst"
    avatarurl = "images/portrait.jpeg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "Here you can find  projects and writings mostly relating to economics, data infrastructures, computer science, and policy."

    hidecredits = true
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/jaredtconnor/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/Jared_ThomasC/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/blog/"
[[menu.main]]
    name = "Projects"
    weight = 2
    url = "/projects/"