include:
  - ./docker-compose.db.yml

services:
  cms:
    build: ./apps/cms
    container_name: cms
    environment:
      - PAYLOAD_SECRET=${PAYLOAD_SECRET}
      - DATABASE_URI=postgressql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - ${CMS_PORT:-5000}:3000
    depends_on:
      - mongo
  
  postgres:
    container_name: ${NAME}-postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - back

  web:
    build: ./apps/web
    container_name: web
    environment:
      - NODE_ENV=production
      - ORIGIN=${ORIGIN}
      - PAYLOAD_SECRET=${PAYLOAD_SECRET}
      - DATABASE_URI=postgressql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - ${WEB_PORT:-5001}:3000
    depends_on:
      db:
        condition: service_healthy
        restart: true
