[build]
  publish = "public"
  command = "make prepare && hugo --source demo --baseURL $URL"

[context.production.environment]
  HUGO_VERSION = "0.55.5"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "make prepare && hugo --source demo --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.55.5"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.55.5"

