baseURL = 'http://localhost:5050'
title = "Signs of Improvement"
author = "Jared Connor"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

enableEmoji = true
hasCJKLanguage = false

pygmentsstyle = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[params]
  sitename = "Signs of Improvement"
  faviconfile = "images/favicon.png"
  highlightjs = true
  highlightjslanguages = ["r", "python", "stan"]
  uselatex = true
  progressively = false
# commentsrepo = "user/repo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.primary]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.primary]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.primary]]
    name = "Projects"
    url = "/projects/"
    weight = 3
[[menu.primary]]
    name = "GitHub"
    url = "https://github.com/jaredtconnor"
    weight = 4
[[menu.primary]]
    name = "Twitter"
    url = "https://twitter.com/home"
    weight = 5
[[menu.primary]]
    name = "Clippings"
    url = "/clippings/"
    weight = 6
